[package]
name = "clocker"
version = "0.1.0"
authors = ["Konnor-Laptop <konnortimmons@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
clap = "2.33.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.45"
chrono = { version = "0.4", features = ["serde"] }